### ISSUE TITLE
Discoverability of Refresh

### ISSUE THREAD

**Issue by GriffinSauce** [mingo-app/mingo#130]
I added a new collection so I was looking for refresh, it was a search but I found the dropdown on the DB:

![image](https://user-images.githubusercontent.com/5630996/72365051-d107e900-36f7-11ea-8311-6bb3bb45cbb4.png)

I expected it to be under Database actions in the second column.

**Comment by tothradoslav** [comment]
yep, this is a good point and we've been thinking of the best logic to implement sync so that users don't even have to think about it.
Currently, sync happens when: 

- connection added / updated
- every 1 hour on background on focused workspace (connection or project)
- on workspace focus
- on manual request

If you have any better ideas, please let me know.

And yes, the button to update database button could be easily added to the second column. Just thinking of a more general solution...

**Comment by GriffinSauce** [comment]
What does "on workspace focus" mean?

**Comment by tothradoslav** [comment]
When you click to change connection or project in the sidebar.

**Comment by Christilut** [comment]
I didn't even realize there is a refresh database button. I kept pressing Sync to do it when I was looking for it..

**Comment by tothradoslav** [comment]
Which "sync" do you mean? I mean which button?

**Comment by Christilut** [comment]
![image](https://user-images.githubusercontent.com/3471363/72429570-92723d00-3790-11ea-8aaf-759bf13e29c2.png)

This one

**Comment by tothradoslav** [comment]
OK, so i renamed this to be "refresh" everywhere and added the link to the second column.

@GriffinSauce how did you add the new collection? Because if you added it in Mingo, it should have refreshed it automatically. If it didn't refresh, it's a bug :)

**Comment by GriffinSauce** [comment]
No outside of Mingo (in my app), so having to refresh was correct :)
