### ISSUE TITLE
Edit project: drag out of input

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#134]
In Edit Project, I'm adding a database but the same thing happens again where I select text and release my mouse when I'm outside the modal and the modal closes... Everything is gone

**Comment by tothradoslav** [comment]
Corrected for this case. 

However this is a global issue. This happens because you "clicked" on the modal overlay, which is set to hide modal. Now I can manually choose whether this should happen or not. I some cases it's a good feature. Was thinking preventing this globally and letting user close only with esc (which is also not desirable in some cases).

**Comment by Christilut** [comment]
But this should happen when I click the mouse on the modal background... Can't you just use `event.target.classList.contains('modal-background')` ? That's how I always do these things

**Comment by tothradoslav** [comment]
It's a drag event kind-of and was trying to distinguish between a direct click and drag-end but couldn't. Then I figured, we still have the ESC button to close it so I removed the click-on-overlay feature and solved the problem.
