### ISSUE TITLE
Nodejs shell error

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#173]
I did a simple `updateMany` call in the nodejs shell but I got this error
![image](https://user-images.githubusercontent.com/3471363/75705251-4e44e880-5cbb-11ea-8fd6-832969e6a01b.png)
In console:
```
error in asyncEvalInContext Cannot convert undefined or null to object 
"db.collection("users").updateMany({
    'mailPreferences.promotions': true
})"
```

My input textarea was reset back to `db.collection("users").find();` which is kind of strange.

And it did show a notification that the call was completed and told me I could undo if I want.

**Comment by Christilut** [comment]
I changed my call to
```
db.collection("users").updateMany(
	{},
	{$set: {
		'mailPreferences.promotions': true
	}},
	{multi: true})
```

And that does work. I guess I'm too used to the Mongoose syntax..

But it wasn't very nice that my input got cleared and it was strange that it showed the undo notification.
And the error the user sees is not very helpful.

**Comment by tothradoslav** [comment]
Ok, thanks. I improved the error reporting, but `Cannot convert undefined or null to object` is what you'll get in such case anyway (just not in console), because that's what Mongo responds. 

Your latest code will now be remembered.

Can't figure out how you got the "undo" notification... I'll need more info on this...
