### ISSUE TITLE
Resize pinned columns

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#195]
Sometimes the pinned columns are really perfect for quickly comparing documents but I really wish I could resize them and make them wider. Sometimes the data I need falls just outside the column :(
![image](https://user-images.githubusercontent.com/3471363/80273951-16648b00-86d7-11ea-9199-f0eef6fb1479.png)

This one shows a good example of the width not being very well distributed

**Comment by tothradoslav** [comment]
When you click on cuePoints, it will give you column options along with some width settings (min, text-width, max). Sometimes the system doesn't handle the default widths properly, but you can manually set it this way. 

If you have a better idea of how to do this, please let me know. Drag-drop was confusing due to column rearrangements.

**Comment by Christilut** [comment]
Is it possible to markers (vertical lines) between the column headers that you can drag to resize?

I think the default widths are usually fine but in some cases it's very nice to be able to resize

**Comment by tothradoslav** [comment]
Done, let me know what you think and / or if the solution is OK, please.
