### ISSUE TITLE
Dump & Restore database quite hidden

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#277]
For me the ability to easily, without using a CLI, dump and restore a database is super powerful and useful. Mingo can do it but for some reason it is super hidden.
I was searching for it again and didn't except to find it after choosing "Dump database"... 

I would rename that option to "Dump & Restore database" or something because there is no indication currently that the user gets the option to dump it into a different database (copy database really).

**Comment by tothradoslav** [comment]
This is a great comment, because it touches my main issue with navigation in Mingo. Basically, there are 2 types of views: collection and database. 

The collection view shows all the options related directly to a collection with "sub-views" in pills at the top (documents, schema, aggregator, etc.)

The database view contains more general database and cross-collection features such as list of all collections, nodeshell and dump. Renaming "Dump database" to a better phrase is a minor tweak but I'm thinking of a better logical layout so that these features are more accessible and obvious in UI.

Do you have any ideas maybe?

**Comment by Christilut** [comment]
No, I just looked at it a bit and I don't have any ideas really

**Comment by tothradoslav** [comment]
For now, I just renamed the option to "Dump & Restore db..." as you suggested
