### ISSUE TITLE
Mongo 3.4

### ISSUE THREAD

**Issue by JMuGT3** [mingo-app/mingo#320]
Hello.

Any chance of using mingo with mongodb 3.4? 

I would probably buy a lifetime license.. but our production servers run mongo 3.4 and I cannot connect them.
The message reads:
"ERROR: Server at ... reports maximum wire version 5, but this version of the Node.js Driver requires at least 6 (MongoDB 3.6)"

**Comment by tothradoslav** [comment]
Well, MongoDB stopped supporting versions 3.6 and lower completely. So the latest driver does not support your version of DB at all. We tried distributing Mingo with both versions of drivers, but dropped the idea due to breaking changes in the latest driver. We might consider building a version with the old driver, but in the meantime, try using Mingo v1.5.0 which has the old driver. Unfortunately, you'll loose out on a lot of great features.

**Comment by JMuGT3** [comment]
Thank you for your answer.

I just tried 1.5 - it does connect, but doesn't load any databases... refresh connection does nothing, there's no database. Mind you, connecting to a server with just a few databases works without a hitch. So I suspect it does not like the production servers with hundreds of databases, each with about 100 collections.

Maybe if you build the latest version with the older driver I will try again.

I guess this issue can be closed.
