### ISSUE TITLE
#after alias

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#347]
I'm trying to get all dates after a certain timestamp, eg `#after2022-01-1` but `after` is not recognized. I think I should use `since` instead.
But since there is a `before`, I think the opposite should be `after`. Can we support both `since` and `after` here?

**Comment by tothradoslav** [comment]
No problem adding those. Just thinking of true meaning. Since and after are different in that since monday includes monday, but after monday doesn’t. But we can have both. 

I was looking for an established standard on wording for this purpose but could not find anything. Do you of anything?

Just a note: After is opposite of before. Since is opposite of until.

**Comment by tothradoslav** [comment]
Hi,

we have just released an RC with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2-rc1

Please, let us know if it's OK or send us feedback. Thank you!

**Comment by tothradoslav** [comment]
We have just released a new version with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2

Please, let us know if it's OK or send us feedback. Thank you!
