### ISSUE TITLE
Exclude certains collections from Compare & Sync

### ISSUE THREAD

**Issue by Jeannot-Muller** [mingo-app/mingo#395]
I have a collection "logins" storing all logins. Obviously, I'll NEVER want to sync this collection. Consequently I have to uncheck this on every check. Not a big deal and I am not sure how to solve this best on your side (as a collection might be deleted one day, etc.). I thought this morning, if a preference list with a few collection names could be a solution?

For instance I can under Preference maintain key names for collections, let's say: "logins", "devStats", etc. If such a collection exists in a db it will not be considered in a check. I'm aware that this implicits that preferences on "project level" might be better (or even needed). Perhaps we could "tag" collections? And on such tags a collection would get ignored. High level request, just an idea ...

**Comment by tothradoslav** [comment]
I can think of two different solutions for this:

1. simply remember the last "checked" collections for next compare / sync action in the future. This would be stored on database level, specifically to the source database. (Whenever you choose the same DB as source in future, the same collections will be checked as the last time).
2. allow saving comparison settings and load them the same way you can save dump/restore settings for use in future.

Since compare / sync is usually done regularly on the same databases, I'd go with solution 1 in this case. It's also simplier to create and to use / comprehend for the user. What do you think?

**Comment by tothradoslav** [comment]
Just using sync, maybe we could even remember the complete last compare / sync settings (source, destination, comparison type).

**Comment by Jeannot-Muller** [comment]
1) would be perfectly fine. Thank you!

**Comment by tothradoslav** [comment]
We actually did both...

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!
