### ISSUE TITLE
Leave headers visible when scrolling

### ISSUE THREAD

**Issue by dlucazeau** [mingo-app/mingo#397]
Hello
It would be more ergonomic if this area was fixed. The scroll makes it invisible.

![image](https://user-images.githubusercontent.com/4538922/167921820-727455f2-a7ed-4e7e-b1e8-34c537274c4f.png)

Regards

**Comment by tothradoslav** [comment]
Thanks for this. We have played with this and other variations, but the space left for the actuall content was too little, especially with many or large documents (when opened). We also experimented with column headers fixed at the top, but this was an HTML / CSS issue due to complex DOM structure. I'll keep this issue open in case we came up with a better solution.

**Comment by dlucazeau** [comment]
The most useful thing for me would be the property names.
We could have a filtering area etc... collapsable.

We could have more space with the implementation of a full screen (F11 in VSCode).

**Comment by Jeannot-Muller** [comment]
What about the option of a floating window for that content (I know not easy to implement, and might habe some cons too). A bit like in the Jetbrains IDEs style, where you can shuffle pieces of windows in the UI around the screen or make them a floating windows.

**Comment by tothradoslav** [comment]
After several attempts with even complex JS functionality, this was not possible to solve without major changes in the DOM structure.  I'm leaving this as won't fix, for now.
