### ISSUE TITLE
Override data type

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#423]
> would be great if we could override the data type on particular fields. E.g. we use timestamps (number) to store date/time (sucks, I know) but that means I don't get nicely formatted Date previews.

source: https://twitter.com/GHengeveld/status/1532699433565048832

**Comment by tothradoslav** [comment]
We discussed this in deep and came to the following conclusion:

If we allowed users to create transform functions on any fields and thus show whatever / however they prefer seeing their data, it would have complicated consequences in many other parts of Mingo's functionality. It would be feasible to make work, however, since Mingo should show real data as much as possible as we are not a CMS, we will be not be doing this in near future. 

A solution to your problem: show the desired format only in a column. First, pin the field as a column (unless already there). Then click on column header, choose Customize and in the "Display value" field, type something along these lines:

dayjs(doc.createdAt).format('MM.DD.YYYY')

- choose any date format you prefer
- choose any field of the doc, in this case it's createdAt

I hope this helps.
