### ISSUE TITLE
mingo.io payment page

### ISSUE THREAD

**Issue by yasaricli** [mingo-app/mingo#45]
Hello;

Congratulations  a beautiful project.

**https://mingo.io/buy?version=0.9.7**

but I'm having a licensing problem. The payment screen on this is also a bit funny.

<img width="1440" alt="Screen Shot 2019-08-21 at 17 41 34" src="https://user-images.githubusercontent.com/1306620/63442125-3acae200-c43b-11e9-9425-1ab5d6b512e7.png">

How can we buy mingo ?

Thanks.

**Comment by achtan** [comment]
hi, we had issues with our server...
your app should be running by now, if not let us know

**Comment by tothradoslav** [comment]
Hi @ yasaricli,

we've been making a lot of progress on Mingo and wanted to let you know to download the latest from our website. It's a hidden version (keeping version number so that active users can test it), so even if you have 0.9.13, the one you would download now has tons of new features and bugfixes.

Keep us posted on any issues / features you'd like.

Thanks, Rad
