### ISSUE TITLE
Better editing flow

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#454]
When a value is `null` it is quite painful to edit it:
![image](https://user-images.githubusercontent.com/3471363/179342971-dfacdee2-d53f-4779-a56c-e63984c255f7.png)
I prefer to use hotkeys, so I hover my mouse over the value and press `E`.

Then I have to switch to my mouse and choose `string` (or whatever I want) from the dropdown.

And for the previous value of `null` this is already quite strange because null doesn't have any alternative value.
Maybe we can improve this with better hotkeys? Maybe `TAB` to go through the types? 
And maybe `null` should have an input field where you can type and it will switch to `string` automatically? If you then empty the input field, it will stay on `string` but you can always swap it back to null.

I think a `TAB` hotkey for quick type changing (or maybe CTRL+1, CTRL+2, etc?) will also be quite nice here.

Or maybe even change it so the types are small tabs above the edit bar, that will make tabbing a lot more intuitive and hotkeys like CTRL+1 etc too (the same behavior as Chrome).

Just some thoughts for a faster workflow.

**Comment by tothradoslav** [comment]
You hit the nail by the head here. I have the same problem :)

I just experimented with this and made a slight change:
- onEdit, by default, the input field gets the focus so that you can type right away
- I just improved this, so that if there's no input field (in case of null), the "type" select will be focused
- then you can use up/down arrow keys to change the type, then press enter - this automatically focuses the input
- not sure if up/down arrow keys in select work this way on windows, too (could you confirm?)
- on mac, when focused into the "type" select, I can even press "s", which selects the "string" value and focuses the value input

Let me know what you think of this. CTRL+1 already focuses the tabs (could be cancelled when editing a field, but too much background magic...). Tab (key) is used for tabindex focusing by default.

I was also thinking of letting enter a value even in case of null and try to guess the type. Numbers or strings would be recognized easily and if value is "null" then it's actually null. I'm just not sure if this would be understood by users in general.

Maybe any other solution?
