### ISSUE TITLE
[linux] new tab is not working on icon click

### ISSUE THREAD

**Issue by kompas-simon** [mingo-app/mingo#47]
distro: ManjaroLinux 18.0.4
desktop env: Gnome 3.32.2

Ctrl + T works

**Comment by tothradoslav** [comment]
We have corrected this, but please check it for me, I can't test on linux. Thanks a lot! (there's a new version 0.9.9 available for download)

**Comment by kompas-simon** [comment]
verified. thanks

**Comment by tothradoslav** [comment]
Hi @kompas-simon,

we've been making a lot of progress on Mingo and wanted to let you know to download the latest from our website. It's a hidden version (keeping version number so that active users can test it), so even if you have 0.9.13, the one you would download now has tons of new features and bugfixes.

Keep us posted on any issues / features you'd like. 

Thanks, Rad
