### ISSUE TITLE
Pin as column multiple times

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#55]
I can do "Pin as column" multiple times on the same field, adding more columns of the same field. I would expect a second pin action would unpin it.

**Comment by tothradoslav** [comment]
There's a reason for this: 

You can customize a pinned column and add formatting or parsing to show, for example, "PAID" in green instead of true and "PENDING" instead of false. Then you could pin the same column and parse / format the value in a different way.  This is edge-case, however, note that you can format a column using values from different fields. For example, I could pin "createdAt" as a regular date and then again the same field, parse it to "how many days ago" using moment() or simple JS parsing. 

See this screenshot: https://cl.ly/9751632f3737

I guess we should explain this to users or make it more clear. Do you have any ideas? 

Thanks for your feedback!

**Comment by Christilut** [comment]
Ah I see, that makes sense yea. Very useful too.

Maybe if a column is already pinned, change the wording in the popup to "Pin as another column" or something. That would make it clear to users that it is intentional.

**Comment by tothradoslav** [comment]
great idea, will be in next release, thanks!
