### ISSUE TITLE
The date time shown for Mexico City Locale is wrong. Legislation changed last year

### ISSUE THREAD

**Issue by mogarick** [mingo-app/mingo#550]
**Describe the bug**
The date time shown for Mexico City Locale is wrong. 
It should be UTC-6 but Mingo is showing it as UTC-5. 
DST legislation changed last year. So There's no more DST for Mexico. Hour time is now UTC-6 for all year.
Mongo Compass is showing it correctly.

**Screenshots**
Correct Dates @ Mongo compass (UTC-6)
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/4414145/229930536-c95a96e9-4487-4422-80b4-f0c10b9c4e1d.png">
Incorrect Dates @ mingo (UTC -5)
<img width="698" alt="image" src="https://user-images.githubusercontent.com/4414145/229930751-8a163ae7-cf81-4e17-b723-32d2e4c6db50.png">

**Desktop (please complete the following information):**
 - Mingo version: 1.11.1
 - OS: MacOS 12.6.4

**Comment by tothradoslav** [comment]
We have updated node.js to the latest version, which is responsible for handling timezones. We also updated dayjs, which we use internally for formatting dates. It is quite difficult to test it properly since we are in a different timezone. 

It still shows UTC-5 for me, but this could be wrong due to my timezone. I will include these changes in the next release. Could you please let me know if it worked? (I will let you know here that the release is out).

**Comment by tothradoslav** [comment]
Hi, this has been included in the latest release v1.12.1:

https://github.com/mingo-app/mingo/releases/tag/v1.12.1

I'm closing this issue, but please let us know if it worked right.

**Comment by mogarick** [comment]
Thank you!
It's working fine now. UTC-6 for This year and month, UTC-5 for last year. and same month. :D
