### ISSUE TITLE
App is showing collections twice

### ISSUE THREAD

**Issue by dimadev01** [mingo-app/mingo#552]
![CleanShot 2023-04-05 at 15 19 41](https://user-images.githubusercontent.com/7450379/230169495-e90f9b7e-5ac8-429d-97f4-f7b6b790d30e.png)

Version 1.11.1

Nothing special, just connected and voilá

**Comment by Vallefor** [comment]
Sometimes I have the same bug but not always.

**Comment by tothradoslav** [comment]
Thanks. And what happens when you click to refresh db? Do the duplicates disappear? I'm looking into the issue now.

**Comment by dimarixsus** [comment]
> 

Nope, they are still there after the refresh

**Comment by dimarixsus** [comment]
> Thanks. And what happens when you click to refresh db? Do the duplicates disappear? I'm looking into the issue now.

Nope, they are still there after the refresh

**Comment by tothradoslav** [comment]
Seems like we have found the cause for this behaviour. A simple description of the problem:

- each collection has a UUID identifier that is given by mongodb
- these ids should be unique even when you copy or restore a collection
- Mingo relied on these, but it turned out that they don't have to be unique all the time
- we have now changed the way Mingo identifies collections and released a patch for this issue

We recommend the following steps to be taken: 
1. remove the problematic connection from Mingo (I know this is a pain and we are really sorry this, but we can't do a roll-back on this)
2. install the patch
3. add the connection again.

Sorry, again, for the problem caused :(

Please let us know if this worked for you. Link to the new release:

https://github.com/mingo-app/mingo/releases/tag/v1.12.1-rc1

**Comment by dimadev01** [comment]
> Seems like we have found the cause for this behaviour. A simple description of the problem:
> 
> * each collection has a UUID identifier that is given by mongodb
> * these ids should be unique even when you copy or restore a collection
> * Mingo relied on these, but it turned out that they don't have to be unique all the time
> * we have now changed the way Mingo identifies collections and released a patch for this issue
> 
> We recommend the following steps to be taken:
> 
> 1. remove the problematic connection from Mingo (I know this is a pain and we are really sorry this, but we can't do a roll-back on this)
> 2. install the patch
> 3. add the connection again.
> 
> Sorry, again, for the problem caused :(
> 
> Please let us know if this worked for you. Link to the new release:
> 
> https://github.com/mingo-app/mingo/releases/tag/v1.12.1-rc1

Heyy, so good you found the solution! No worries about reinstalling it from my side! I love Mingo, I'm glad you found the bug!

**Comment by dimadev01** [comment]
> > Seems like we have found the cause for this behaviour. A simple description of the problem:
> > 
> > * each collection has a UUID identifier that is given by mongodb
> > * these ids should be unique even when you copy or restore a collection
> > * Mingo relied on these, but it turned out that they don't have to be unique all the time
> > * we have now changed the way Mingo identifies collections and released a patch for this issue
> > 
> > We recommend the following steps to be taken:
> > 
> > 1. remove the problematic connection from Mingo (I know this is a pain and we are really sorry this, but we can't do a roll-back on this)
> > 2. install the patch
> > 3. add the connection again.
> > 
> > Sorry, again, for the problem caused :(
> > Please let us know if this worked for you. Link to the new release:
> > https://github.com/mingo-app/mingo/releases/tag/v1.12.1-rc1
> 
> Heyy, so good you found the solution! No worries about reinstalling it from my side! I love Mingo, I'm glad you found the bug!

It worked, thanks!
