### ISSUE TITLE
Very strange behavior when switching between connections in one project

### ISSUE THREAD

**Issue by Vallefor** [mingo-app/mingo#553]
**Describe the bug**
I have 1 project and two conntctions (prod and dev) thet using ssh-tunel.
Every connections have no passwords and have the same connection uri.
The only difference between them is SSH-tunel (different IPs but the same key)

When I start mingo and choose prod connection and then switch to dev I will see all data from the first connection (prod). To switch to dev I need to close all tabs restart mingo and choose dev connection.

To reproduce it:
1. Create project
2. Create first connection with ssh tunel and connection uri like this: mongodb://localhost:27017/test-db
3. Create second connection with ssh tunel and connection uri like this: mongodb://localhost:27017/test-db
4. Create collections with the same name on each DB.
5. Add some different data in each collection
6. Choose project and open collection from first connection.
7. Switch to collecteon from second connection - you will see the same data

**Desktop (please complete the following information):**
 - Mingo version: 1.11.0
 - OS: Linux

**Comment by tothradoslav** [comment]
Thank you for this. So far I have not been able to reproduce your issue with the steps you provided. But i'm still trying...

Could you please let me know what you mean by "switch to collection from second connection"? I mean, where exactly do you click to "switch"? 

Does this also happen when you open the collection in first connection in one tab and the other in another tab?

**Comment by tothradoslav** [comment]
Seems like we have found the cause for this behaviour. A simple description of the problem:

- each collection has a UUID identifier that is given by mongodb
- these ids should be unique even when you copy or restore a collection
- Mingo relied on these, but it turned out that they don't have to be unique all the time
- we have now changed the way Mingo identifies collections and released a patch for this issue

We recommend the following steps to be taken: 
1. remove the problematic connection from Mingo (I know this is a pain and we are really sorry this, but we can't do a roll-back on this)
2. install the patch
3. add the connection again.

Sorry, again, for the problem caused :(

Please let us know if this worked for you. Link to the new release:

https://github.com/mingo-app/mingo/releases/tag/v1.12.1-rc1

**Comment by Vallefor** [comment]
I record a video with demonstration. I think it should be more clearly now :) Let me know if you need somethig more!

https://user-images.githubusercontent.com/1270687/230879571-e8b8b844-35bc-49f0-a579-db526c7556fb.mp4

Also I am ALMOST sure the root of this bug.
As you can see it lsof says mingo opens two connection to same server.

```
~ sudo lsof -i -P | grep mingo | grep ":22"
mingo     346024 vallefor   45u  IPv4 3850730      0t0  TCP manjaro:58824->static.103.7.181.135.clients.your-server.de:22 (ESTABLISHED)
mingo     346024 vallefor   49u  IPv4 3848913      0t0  TCP manjaro:55622->static.103.7.181.135.clients.your-server.de:22 (ESTABLISHED)
```

**Comment by tothradoslav** [comment]
this is great, thanks, will investigate and let you know!

**Comment by tothradoslav** [comment]
This may actually be related to #555, which we have already patched for testing purposes, but I only created a osx build. Which linux build are you using so that i could build the one for you to test it, too. Thank you

**Comment by tothradoslav** [comment]
Try here:

https://github.com/mingo-app/mingo/releases/tag/v1.12.1-rc1

**Comment by Vallefor** [comment]
I have checked AppImage v1.12.1-rc1. The bug still there :(

**Comment by Vallefor** [comment]
And yes, the bug is very similar that described in https://github.com/mingo-app/mingo/issues/555. With one exception - all my connections are remote.

**Comment by tothradoslav** [comment]
@Vallefor sorry, I forgot to mention, that you will have to remove these connections that have the issue and add them pack into Mingo. I understand that this is a very bad UX, but the UUIDs we used for were not safe enough in some cases. Please try to remove those two connections, then add them back again and try it (on 1.12.1 please).

Please let me know. Thank you and sorry again :(

**Comment by Vallefor** [comment]
@tothradoslav Ok. I deleted project (with name "bug" in my case). Then created it and create connections from scratch. Bug still there :cry:
And lsof shows that mingo opens tunnel for only one server.

**Comment by tothradoslav** [comment]
sorry for my late response, we are trying to figure out the problem and will let you know. thanks!

**Comment by tothradoslav** [comment]
@Vallefor I just realized, that since you are using RC version, you have access to devtools inside Mingo. Could you please help me with the following?

1. restart mingo
2. open devtools (Option + Command + i on a mac,  not sure about linux)
3. in console, there should be some notes of "Reusing existing tunnel" or "Creating new tunnel", could you send me those? (nothing private, it's a md5 of ssh config)

Could you send these to me? Or a screenshot of console logs if nothing private is shown (should not be)

Thank you

**Comment by Vallefor** [comment]
@tothradoslav Sure.

I have restarted Mingo.
I have opened dev tools (ctrl + shift + i).
Switched multiple times with prod/dev.

I have two log strings with "tunnel" word:
Creating new tunnel 601b24da0429569e124edcd79f5003cd
Creating new tunnel 6b3dc60005e5d44d04e1b56375f276b2

![2023-04-17_17-55](https://user-images.githubusercontent.com/1270687/232477204-838303e3-fca3-44ad-95ac-94cb996a8fb6.png)

**Comment by Vallefor** [comment]
@tothradoslav 
Btw, I can give you access to my PC via Teamviewer or other software if it helps to determine the reason of the problem.

**Comment by tothradoslav** [comment]
This would be pretty helpfull. If you can send me an email to info@mingo.io, we could work on that from there. Thank you!

**Comment by tothradoslav** [comment]
Hi, any news on this? I'd like to solve this really weird issue :)

**Comment by Vallefor** [comment]
Hi. I have installed 1.12.1 version today and noticed that the bug is gone. But I remember that at 1.12.1-rc bug was reproducible. Strange but we can close this issue. Thanks for your work!

**Comment by tothradoslav** [comment]
Thanks, I will keep it open to be able to include this in our release notes.

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.13.1
