### ISSUE TITLE
Tabs missing their titles

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#554]
Some tabs have started losing their titles:

![image](https://user-images.githubusercontent.com/518013/230430096-731d36f1-d4c2-4baa-be3d-c3adff30cf11.png)

This is on macOS 13.3, Mingo version 1.12.0.

**Comment by tothradoslav** [comment]
Thank you. Does this happen when you open a tab or were these older tabs from previous version of Mingo? What happens when you close and reopen the tabs?

**Comment by brianlukoff** [comment]
I'm not positive but they might have been tabs from the previous version. (It hasn't happened again since this morning with reopened tabs.)

**Comment by tothradoslav** [comment]
We have changed the way we identify collections (using the original UUID of the collection upon creation - this is provided by MongoDB) and your issue may be a sideaffect of this change. 

If this is the case, we'd have to close all tabs upon migration, but users could lose their work status - since Mingo can't find the original collection any more. We did this to stabilize some functionality when refreshing collections from a DB. So I think, in this case, we'll be better off keeping it as is (with this error). It's a one-time problem with no undo option for now. I'm sorry about that :(

**Comment by tothradoslav** [comment]
I can now confirm, that this is the case. And it also happens whenever a collection is dropped and recreated, too. For example after mongorestore operation. We'll have to come up with a better way to identify collections (name is not completely sufficient)

**Comment by brianlukoff** [comment]
No problem -- not a big deal if it's just a one-time thing!

**Comment by tothradoslav** [comment]
I changed the way we identify collections now, hopefully it will be much more stable. It will available in next patch.

**Comment by tothradoslav** [comment]
As mentioned, this issue affected users of v1.12.0, with an incorrect migration, which cannot be undone. Fortunately this is a minor issue, fixed by closing those tabs.
