### ISSUE TITLE
[FR] convert timestamp to readable format

### ISSUE THREAD

**Issue by AlexeySpiridonov** [mingo-app/mingo#572]
please )

**Comment by tothradoslav** [comment]
Hi, what exactly do you mean? Are you storing dates as timestamps in DB and would like to handle these as dates?

**Comment by AlexeySpiridonov** [comment]
Sorry, I should have written in more detail.   

It would be great to show UI timestamp as readable date/time

16244324234 [i] - like this, and when hovered over, show the normal date

**Comment by tothradoslav** [comment]
Ok, are you storing it as a number or a string?

If a number, we would have to be able to guess when it's a date, not a large number.

**Comment by AlexeySpiridonov** [comment]
The current timestamp is 10 characters long.   The range 10******** - 19******** will cover the period from 2004 to 2032.  

if let(t)==10 &&  t>1000000000 && t<1900000000 { showAsDate(t)}

Even if the [i] sign is shown incorrectly somewhere, I think it's okay, and it will be clear why the sign is shown. 

But the convenience of using this will add a lot.  

You can also check if the name of the field has **time** substring ;)

**Comment by tothradoslav** [comment]
OK. We are thinking of a more global solution for such use-cases, because different people will have weird ways of storing data. For example, I'm using a number 20230505 to store a date, where I don't need time granularity and timezones a are a problem. 

For such cases, we want to add a custom parsing functionality where you could enter the above condition you wrote and a way to handle such values. 

But for starters, we'll just try to implement what you wrote. Thanks!

**Comment by tothradoslav** [comment]
Done, will look like this (date format based on settings):

<img width="640" alt="Screenshot 2024-08-03 at 14 21 56" src="https://github.com/user-attachments/assets/31dbe90e-bdf3-4047-adbe-9888f3ab50f9">

**Comment by tothradoslav** [comment]
This issue is fixed / available in the new release v1.14.1

https://github.com/mingo-app/mingo/releases/tag/v1.14.1

Please reopen this issue if necessary.
