### ISSUE TITLE
Dump & Restore from saved action doesn't work if target database was recreated

### ISSUE THREAD

**Issue by jmisur** [mingo-app/mingo#585]
I saved a simple dump & restore action:
- Copy collections to an existing database
- Source: Remote MongoDb 6
- Collections: subset selected
- Destination: Local MongoDb 6, database "test"
- drop: true

Problem:
When I drop entire database "test" and then create new with the same name, the Load action get's stuck at Destination step. This step is unchecked but also stuck as clicking on "Change" button does nothing and I cannot continue.

I would expect the Load action to pick up the target database even if it was dropped and recreated in the meantime.

**Comment by tothradoslav** [comment]
Thank you for this. Mingo has it's own ids for databases and it was using these to store the dump settings. I have changed this so that the database names are stable across drop/recreate.

However, you would still loose the dump if you recreated the underlying connection. 

Will be out in next release.

**Comment by tothradoslav** [comment]
We have just released a release candidate with this issue corrected. Please check it out here: https://github.com/mingo-app/mingo/releases/tag/v.1.13.4

**Comment by jmisur** [comment]
FYI this problem is again present in 1.13.5
