### ISSUE TITLE
"Edit value" on an object incorrectly converts dates to strings

### ISSUE THREAD

**Issue by bverhoeven** [mingo-app/mingo#608]
**Describe the bug**

Inline editing an object (through "Edit value") converts date fields within that object to strings.

**Screenshots**

Note that, initially, the fields are dates/timestamps:

![image](https://github.com/mingo-app/mingo/assets/1443431/9f1b5727-08b4-48cc-bdb4-52c23ff4e235)

When right clicking on the field and using "Edit value" option, a textbox appears containing a JSON representation of the field:

![image](https://github.com/mingo-app/mingo/assets/1443431/9efa64af-763b-48b5-a22f-46ab15369aeb)

Once saved, the fields that were once dates/timestamps are now strings.

![image](https://github.com/mingo-app/mingo/assets/1443431/7ebca8bf-b784-4df1-af2e-4a6f046456fb)

**Desktop (please complete the following information):**
 - Mingo version: 1.13.3
 - OS: Windows 11

**Comment by tothradoslav** [comment]
Thank you, we have improved it, now it shows new Date() instead of simple string and when submitted, it's evaluated properly.

One minor comment: ideally, you should not be editing the object "lease" but the actual sub-values directly, such as the expiresAt. Just dbl-click the "expiresAt" and edit this directly, it will know it's a date, not an object.

**Comment by tothradoslav** [comment]
We have just released a release candidate with this issue corrected. Please check it out here: https://github.com/mingo-app/mingo/releases/tag/v.1.13.4

**Comment by bverhoeven** [comment]
Thanks for that elegant solution! I did some preliminary testing with 1.13.4-rc1 and from what I can see everything now works as expected.
