### ISSUE TITLE
The Pro tips popup is misaligned

### ISSUE THREAD

**Issue by GriffinSauce** [mingo-app/mingo#83]
It's too low:

<img width="136" alt="Screenshot 2019-12-12 at 13 45 33" src="https://user-images.githubusercontent.com/5630996/70713187-bc45c900-1ce5-11ea-8640-4d02e00b1abc.png">

**Comment by tothradoslav** [comment]
@GriffinSauce  I have released a new "hidden" version, with all issues marked "next release" done. I didn't bother creating an RC version, because we stopped any marketing for now, so there are few downloads now.

This version includes the devtools, so you can see any logs / errors, for better reporting. Opens / closes just like in Chrome.

Please check all your open issues marked for "next release" and close / comment on them. Thanks for all feedback!

**Comment by GriffinSauce** [comment]
Looks good, fixed!
